[execution_conf]
    charusters_nums = 5
    export_to_json = true
    export_to_json_file = "output/charusters.json"

[char_conf]
    gen_name = true
    gen_surname = true
    gen_nickname = true
    gen_birthdate = true
    gen_birthplace = true
    gen_description = false
    gen_image = true
    gen_collection = true
    gen_profession = true
    gen_hobbies = true
    gen_props = true
    gen_levels = true
    gen_stats = true

[values_conf]
    collection_name = "Z8mbit"
    names_file = "resources/names"
    surnames_file = "resources/surnames"
    nicknames_file = "resources/adjectives"
    birthplaces_file = "resources/country_cities"
    hobbies_file = "resources/hobbies"
    professions_file = "resources/professions"
    props_file = "resources/properties.json"
    stats_file = "resources/levels_stats"
    levels_file = "resources/levels_stats"
    images_folder = "/Users/firegloves/workspace/NFTGonarator/output"
    description_files = "resources/descriptions"
    birthdate_min_year = 1920
    birthdate_max_year = 2010
